services:
  db:
    image: mysql:8.4
    build: ./mysql
    env_file: ./.env
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test:
        - CMD-SHELL
        - >
          mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" -Nse "SELECT ok FROM ${DB_DATABASE}.__init_ok LIMIT 1" | grep -qx 1
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 2s

  node:
    build: ./app
    working_dir: /app
    command: npm run start
    env_file: ./.env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes: 
  dbdata: {}
