CREATE DATABASE IF NOT EXISTS blog;
CREATE USER IF NOT EXISTS '${APP_USER}'@'%' IDENTIFIED BY '${APP_PASSWORD}';
GRANT ALL PRIVILEGES ON blog.* TO '${APP_USER}'@'%';
FLUSH PRIVILEGES;

USE blog;
-- Create Posts table
CREATE TABLE IF NOT EXISTS Posts (
    PostID INT NOT NULL AUTO_INCREMENT,
    Title VARCHAR(255) NOT NULL,
    Content TEXT NOT NULL,
    Author_id INT NOT NULL,
    Created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PostID)
);

-- Create RequestLogs table
CREATE TABLE IF NOT EXISTS RequestLogs (
    id INT NOT NULL AUTO_INCREMENT,
    timestamp DATETIME NOT NULL,
    ip VARCHAR(45) NOT NULL,
    method VARCHAR(10) NOT NULL,
    url TEXT NOT NULL,
    userAgent TEXT NULL,
    referrer TEXT NULL,
    status INT NOT NULL,
    contentLength INT NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS __init_ok (ok TINYINT PRIMARY KEY);
REPLACE INTO __init_ok (ok) VALUES (1);
